// <auto-generated />
using System;
using IndustrialOS.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IndustrialOS.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IndustrialOS.Domain.Entities.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cnpj")
                        .HasColumnType("text");

                    b.Property<string>("Contato")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Endereco")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("clientes", (string)null);
                });

            modelBuilder.Entity("IndustrialOS.Domain.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Cnpj")
                        .HasColumnType("text");

                    b.Property<string>("Config")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<Guid?>("MatrizId")
                        .HasColumnType("uuid");

                    b.Property<string>("NomeFantasia")
                        .HasColumnType("text");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("empresas", (string)null);
                });

            modelBuilder.Entity("IndustrialOS.Domain.Entities.FuncaoMaoObra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("CustoHh")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Nome")
                        .IsUnique();

                    b.ToTable("funcoes", (string)null);
                });

            modelBuilder.Entity("IndustrialOS.Domain.Entities.Obra", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Contrato")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataInicio")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("FrenteServico")
                        .HasColumnType("text");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Local")
                        .HasColumnType("text");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrdemServico")
                        .HasColumnType("text");

                    b.Property<string>("PrazoPagamento")
                        .HasColumnType("text");

                    b.Property<string>("ResponsavelPadrao")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.ToTable("obras", (string)null);
                });

            modelBuilder.Entity("IndustrialOS.Domain.Entities.ObraItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DataFim")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DataInicio")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Disciplina")
                        .HasColumnType("text");

                    b.Property<decimal?>("HhPrevisto")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ObraId")
                        .HasColumnType("uuid");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<decimal?>("QtdPrevista")
                        .HasColumnType("numeric");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Unidade")
                        .HasColumnType("text");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ObraId");

                    b.ToTable("obra_itens", (string)null);
                });

            modelBuilder.Entity("IndustrialOS.Domain.Entities.Rdo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AprovadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AprovadoPor")
                        .HasColumnType("text");

                    b.Property<string>("Assinaturas")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Clima")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Data")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiaSemana")
                        .HasColumnType("text");

                    b.Property<string>("Dificuldades")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("EnviadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("EnviadoPor")
                        .HasColumnType("uuid");

                    b.Property<string>("Jornada")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<Guid>("ObraId")
                        .HasColumnType("uuid");

                    b.Property<string>("Ocorrencias")
                        .HasColumnType("text");

                    b.Property<string>("PdfR2Key")
                        .HasColumnType("text");

                    b.Property<string>("Planejamento")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("ProximoDia")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid?>("ResponsavelUsuarioId")
                        .HasColumnType("uuid");

                    b.Property<int>("Revisao")
                        .HasColumnType("integer");

                    b.Property<string>("Seguranca")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("TokenAprovacao")
                        .HasColumnType("text");

                    b.Property<string>("Turno")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TenantId");

                    b.HasIndex("ObraId", "Numero")
                        .IsUnique();

                    b.ToTable("rdos", (string)null);
                });

            modelBuilder.Entity("IndustrialOS.Domain.Entities.RdoMidia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .HasColumnType("text");

                    b.Property<double?>("Lat")
                        .HasColumnType("double precision");

                    b.Property<double?>("Lon")
                        .HasColumnType("double precision");

                    b.Property<string>("R2Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RdoId")
                        .HasColumnType("uuid");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RdoId");

                    b.ToTable("rdo_midia", (string)null);
                });

            modelBuilder.Entity("IndustrialOS.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Cnpj")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Plano")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("IndustrialOS.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<Guid?>("EmpresaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Funcao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique();

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("IndustrialOS.Domain.Entities.UsuarioObra", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ObraId")
                        .HasColumnType("uuid");

                    b.HasKey("UsuarioId", "ObraId");

                    b.ToTable("usuario_obras", (string)null);
                });

            modelBuilder.Entity("IndustrialOS.Domain.Entities.Rdo", b =>
                {
                    b.OwnsMany("IndustrialOS.Domain.Entities.RdoEfetivo", "Efetivo", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Entrada")
                                .HasColumnType("text");

                            b1.Property<string>("Funcao")
                                .HasColumnType("text");

                            b1.Property<string>("HoraExtra")
                                .HasColumnType("text");

                            b1.Property<string>("Obs")
                                .HasColumnType("text");

                            b1.Property<int>("Quantidade")
                                .HasColumnType("integer");

                            b1.Property<Guid>("RdoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Saida")
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("RdoId");

                            b1.ToTable("rdo_efetivo", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RdoId");
                        });

                    b.OwnsMany("IndustrialOS.Domain.Entities.RdoParalisacao", "Paralisacoes", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Descricao")
                                .HasColumnType("text");

                            b1.Property<string>("Fim")
                                .HasColumnType("text");

                            b1.Property<string>("Inicio")
                                .HasColumnType("text");

                            b1.Property<string>("Motivo")
                                .HasColumnType("text");

                            b1.Property<Guid>("RdoId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("RdoId");

                            b1.ToTable("rdo_paralisacoes", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RdoId");
                        });

                    b.OwnsMany("IndustrialOS.Domain.Entities.RdoRecurso", "Recursos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Equipamento")
                                .HasColumnType("text");

                            b1.Property<string>("Horas")
                                .HasColumnType("text");

                            b1.Property<string>("Obs")
                                .HasColumnType("text");

                            b1.Property<int>("Quantidade")
                                .HasColumnType("integer");

                            b1.Property<Guid>("RdoId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("RdoId");

                            b1.ToTable("rdo_recursos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RdoId");
                        });

                    b.OwnsMany("IndustrialOS.Domain.Entities.RdoRetrabalho", "Retrabalho", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("AcaoCorretiva")
                                .HasColumnType("text");

                            b1.Property<string>("Atividade")
                                .HasColumnType("text");

                            b1.Property<string>("Causa")
                                .HasColumnType("text");

                            b1.Property<string>("Descricao")
                                .HasColumnType("text");

                            b1.Property<decimal?>("Horas")
                                .HasColumnType("numeric");

                            b1.Property<string>("Local")
                                .HasColumnType("text");

                            b1.Property<string>("Origem")
                                .HasColumnType("text");

                            b1.Property<int>("Pessoas")
                                .HasColumnType("integer");

                            b1.Property<decimal?>("Quantidade")
                                .HasColumnType("numeric");

                            b1.Property<Guid>("RdoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Unidade")
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("RdoId");

                            b1.ToTable("rdo_retrabalho", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RdoId");
                        });

                    b.OwnsMany("IndustrialOS.Domain.Entities.RdoServico", "Servicos", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<string>("Atividade")
                                .HasColumnType("text");

                            b1.Property<string>("EtapasFeitas")
                                .IsRequired()
                                .HasColumnType("jsonb");

                            b1.Property<string>("Local")
                                .HasColumnType("text");

                            b1.Property<string>("MotivoHold")
                                .HasColumnType("text");

                            b1.Property<Guid?>("ObraItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Obs")
                                .HasColumnType("text");

                            b1.Property<decimal?>("PctInformado")
                                .HasColumnType("numeric");

                            b1.Property<decimal?>("QtdExec")
                                .HasColumnType("numeric");

                            b1.Property<Guid>("RdoId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Status")
                                .HasColumnType("text");

                            b1.Property<string>("Unidade")
                                .HasColumnType("text");

                            b1.HasKey("Id");

                            b1.HasIndex("RdoId");

                            b1.ToTable("rdo_servicos", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RdoId");
                        });

                    b.Navigation("Efetivo");

                    b.Navigation("Paralisacoes");

                    b.Navigation("Recursos");

                    b.Navigation("Retrabalho");

                    b.Navigation("Servicos");
                });

            modelBuilder.Entity("IndustrialOS.Domain.Entities.RdoMidia", b =>
                {
                    b.HasOne("IndustrialOS.Domain.Entities.Rdo", null)
                        .WithMany()
                        .HasForeignKey("RdoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
